apiVersion: v1
kind: Service 
metadata: 
   name: student-service 
   namespace: data 
spec:
  selector:
    app: student
  type: NodePort 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: student-cont