apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  initContainers:
  - name: init-myservice
    image: busybox
    command: ['sh', '-c', 'echo Initializing my service... > /mnt/shared/data.txt && sleep 5']
    volumeMounts:
    - name: shared-data
      mountPath: /mnt/shared
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'cat /mnt/shared/data.txt && sleep 3600']
    volumeMounts:
    - name: shared-data
      mountPath: /mnt/shared
