apiVersion: v1
kind: Pod 
metadata: 
  name: new-nginxpod
  namespace: nginxns
  labels:   
    app: myapp 
spec: 
    containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort : 80
              protocol : TCP
              name: nginx