apiVersion: v1 
kind: Service
metadata:
    name: new-nginxservice
    namespace:  nginxns
spec: 
    type: NodePort
    selector: 
      app: myapp
    ports: 
        - port: 80 
          targetPort: 80
          protocol: TCP 
    