apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: replica-set
  labels:
    app: nginx-app

spec:
  replicas: 5
  selector:
    matchExpressions:
   - {key: app, operator: In, values: [nginx-app, replica],}
      
  template:
    metadata:
      labels:
        name: nginx-app
        app: nginx-app

    spec:
      containers:
      - name: nginx-app
        image: nginx:latest
        ports:
        - containerPort: 80
          protocol: TCP


