apiVersion: v1
kind: ReplicationController

metadata:
  name: replication-controller
  labels:
    app: controller

spec:
  replicas: 4
  selector:
    app: controller

  template:
    metadata:
      labels:
        app: controller
        name: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: nginx:latest
        ports:
        - containerPort: 80
          protocol: TCP