apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: dev
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "2Gi"
        cpu: "2"



#kubectl apply -f test-pod.yaml


#Check the current resource usage in the dev namespace: kubectl get resourcequota dev-quota -n dev -o yaml

