apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: "10Gi"
    limits.cpu: "8"
    limits.memory: "20Gi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ops-quota
  namespace: ops
spec:
  hard:
    pods: "20"
    requests.cpu: "10"
    requests.memory: "25Gi"
    limits.cpu: "20"
    limits.memory: "50Gi"


#kubectl apply -f dev-quota.yaml
#kubectl apply -f ops-quota.yaml


 
# To verify that the resource quotas are correctly applied, you can describe the resource quotas for each namespace:
                    #  kubectl describe resourcequota dev-quota -n dev
                    #    kubectl describe resourcequota ops-quota -n ops



