apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: dev
  name: dev-rolebinding
subjects:
- kind: User
  name: dev-user  # Replace with actual user name or group
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ops
  name: ops-rolebinding
subjects:
- kind: User
  name: ops-user  # Replace with actual user name or group
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ops-role
  apiGroup: rbac.authorization.k8s.io
