apiVersion: v1
kind: Service 
metadata: 
   name: 2048-service 
   namespace:  game
spec:
  selector:
    app: mygame
  type: NodePort 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: game-cont