apiVersion: v1
kind: Pod  
metadata :
   name: nginx-pod
   labels: 
       app: tejal
spec:
    containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          protocol: TCP
      - name: tomcat
        image: tomcat:latest
        ports:
        - containerPort: 8080
          protocol: TCP

          
