apiVersion: v1
kind: Service
metadata:
  name: nodeportservice
spec: 
   type: NodePort
   selector:
     app: tejal
   ports:
      - name: nginx 
        port: 80
        protocol: TCP 
        targetPort: 80
      - name: tomcat 
        port: 8080
        protocol: TCP 
        targetPort: 8080
