apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: deamonset
  labels:
    app: deamon
spec:
  selector:
    matchLabels:
      app: deamon
  template:
    metadata:
      labels:
        app: deamon
    spec:
      containers:
      - name: deamon
        image: tomcat:latest
        ports:
        - containerPort: 8080
          protocol: TCP
----
apiVersion: v1
kind: Service
metadata:
  name: nodeportservice
spec: 
   type: NodePort
   selector:
     app: deamon
   ports:
      - name: nginx 
        port: 80
        protocol: TCP 
        targetPort: 80
      - name: tomcat 
        port: 8080
        protocol: TCP 
        targetPort: 8080
