apiVersion: apps/v1
kind:  StatefulSet
metadata: 
  name: statefull
  labels:
    app: ss
spec:
    selector: 
      matchLabels: 
          app: ss
    replicas: 4
    template:
      metadata:
        labels:
          name: mdb
          app: ss
      spec:
        containers:
          - name: mysql
            image: mysql
            ports:
                - containerPort: 3306
                  protocol: TCP
            env:
                 - name: MYSQL_ROOT_PASSWORD
                   valueFrom:
                        secretKeyRef:
                          name: secret
                          key: rootpw